// features/work-sessions/mock/workSessions.mock.ts

export type EmployeeListItem = {
	id: string;
	name: string;
};

export type ProjectListItem = {
	id: string;
	name: string;
};

export type WorkSessionMonthItem = {
	id: string;
	employeeId: string;
	projectId: string | null;

	// Useful DTO field for worksheet/table rendering.
	// It can later be generated by the API from startTime.
	date: string;

	startTime: string;
	endTime: string | null;
	totalMinutes: number | null;

	status: "active" | "completed" | "approved";
};

export const mockEmployees: EmployeeListItem[] = [
	{ id: "emp-1", name: "Jonas Jonaitis" },
	{ id: "emp-2", name: "Petras Petraitis" },
	{ id: "emp-3", name: "Tomas Tomaitis" },
	{ id: "emp-4", name: "Marius Marijus" },
	{ id: "emp-5", name: "Darius Darius" },
];

export const mockProjects: ProjectListItem[] = [
	{ id: "project-1", name: "Angaras Klaipėda" },
	{ id: "project-2", name: "Sandėlis Panevėžys" },
	{ id: "project-3", name: "Angaras Kaunas" },
];

export const mockWorkSessions: WorkSessionMonthItem[] = [
	{
		id: "session-1",
		employeeId: "emp-1",
		projectId: "project-1",
		date: "2026-09-01",
		startTime: "2026-09-01T08:00:00+03:00",
		endTime: "2026-09-01T17:00:00+03:00",
		totalMinutes: 480,
		status: "completed",
	},
	{
		id: "session-2",
		employeeId: "emp-1",
		projectId: "project-1",
		date: "2026-09-02",
		startTime: "2026-09-02T08:00:00+03:00",
		endTime: "2026-09-02T16:30:00+03:00",
		totalMinutes: 450,
		status: "completed",
	},
	{
		id: "session-3",
		employeeId: "emp-1",
		projectId: "project-2",
		date: "2026-09-03",
		startTime: "2026-09-03T08:00:00+03:00",
		endTime: "2026-09-03T12:00:00+03:00",
		totalMinutes: 240,
		status: "completed",
	},
	{
		id: "session-4",
		employeeId: "emp-1",
		projectId: "project-3",
		date: "2026-09-03",
		startTime: "2026-09-03T12:30:00+03:00",
		endTime: "2026-09-03T16:30:00+03:00",
		totalMinutes: 240,
		status: "completed",
	},

	{
		id: "session-5",
		employeeId: "emp-2",
		projectId: "project-1",
		date: "2026-09-01",
		startTime: "2026-09-01T07:30:00+03:00",
		endTime: "2026-09-01T16:30:00+03:00",
		totalMinutes: 480,
		status: "approved",
	},
	{
		id: "session-6",
		employeeId: "emp-2",
		projectId: "project-1",
		date: "2026-09-02",
		startTime: "2026-09-02T08:00:00+03:00",
		endTime: "2026-09-02T17:00:00+03:00",
		totalMinutes: 480,
		status: "completed",
	},
	{
		id: "session-7",
		employeeId: "emp-3",
		projectId: "project-2",
		date: "2026-09-01",
		startTime: "2026-09-01T08:00:00+03:00",
		endTime: "2026-09-01T15:00:00+03:00",
		totalMinutes: 360,
		status: "completed",
	},
	{
		id: "session-8",
		employeeId: "emp-3",
		projectId: "project-2",
		date: "2026-09-03",
		startTime: "2026-09-03T08:00:00+03:00",
		endTime: "2026-09-03T17:00:00+03:00",
		totalMinutes: 480,
		status: "completed",
	},
];
